### ISSUE TITLE
Serve UI on all (functionally) interfaces

### ISSUE THREAD

**Issue by adrum** [tesla-android/flutter-app#8]
I plugged my pi in to my switch for ethernet connectivity, but the UI appears to be only accessible when on the Pi's wifi network. The UI is looking for 9.9.0.1 as the host. Would be nice if the resources loaded by the webpage were relative to the initial page. aka the LAN IP on my network.

The initial webpage loads fine, but the web socket connection fails. The UI reads a message "Virtual touchscreen not available. Wait for Android to boot up."

Originally in https://github.com/tesla-android/issue-tracker/issues/109

**Comment by mikegapinski** [comment]
thanks for the ticket!

**Comment by mikegapinski** [comment]
Done, will be released with the next version

**Comment by adrum** [comment]
@mikegapinski I was doing some testing this weekend outside the car and noticed the API isn't working unless the browser hostname was device.teslaandroid.com. Hitting the IP directly served the UI, but the API was seemingly not working. The `/api/health` and `/api/displayState` endpoint just returns a 404. I was able update to update my computer's hosts file to circumvent the issue.

<img width="592" alt="image" src="https://github.com/tesla-android/flutter-app/assets/1464185/86c39a3e-d670-414d-a33f-8f1b00cc1b24">
